language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: Z9j759uhtxbFKwCMmqK9oaMmSn0ny+nnPGlniQA6WkaI8EcV5Ok6/b1xYM/31WZy3SOL6wib6NR4dE5fgBYNQi6WXeaKa+BHjxM9qplEvMQiDPmqIqYqngYorBvE5YgFjc0FQtrFn+l8/hFHaunZNiVLMyTAEVSnOpKlnDsi4iRsDz7/e1ICvzLxlLFMXnf86nzvauowXDPPZJVhsb6q/dB6Q72gXhObfXB48cANrr/DZbyBmSzcliXtSsnSTOkp4xQ+4jc+M0yvW6acySfYR0olWO/qItE42PmtS4p6eNy7kFtBq6/gYMAjvgGg0lLrUtKjSZzEOPxpKR/uM+l1jTFyYD+o8LqXqG+x4Bty8IYJPCMqEDvSJN1sNh13VP6MQdAvSGedCwt7Cv0EHQvtLexQD8Qelq3yCp9sis/jmXhEKZdK0sSIDfTfBeiWbB9+frwTkXW5p5Jq90H4QsgmwKVuM6ux6MoTxNPXY6j3EwEkpUSAFF8waiAsLgM0XhlMBmvOY4wGXGfjBgR3vBT5zBEapSkaFBg0gh2fphSZpfLJeTPxR1j72wp56eYugvuXNjwsOLVrItHKGcqKmAvk/kfvJgCw6Ln5wvfd/MW1aPhRNHKs/2XR2wTpI7oZq695p9w4jM8ujY206xaPjrLUQUJd1uwFykgsNisOJWKTFBc=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Y8CXvJ/X2ft/5VrDUBYTnFJLLfSxVXILiEVtG71mAmY6TBoxUnVGfLYHCztFYx1MceGK8AM6F6m20qcHZ8SLMyx8TmYBjePJdRQuIFjbCiWLzOBxpJfFw2d4atAP081+YKH9tchCUfNrJ9cFlPwnD4YujX+2MiKAuAgu/0ys72F33bynHURS8Cr3tIKOCQRotWlkDKp6XNWa9XKrlQDUd88Dre7TM+lJ9LvtbnVHg1Gl344hFyGyBEOXLfYp/m7WqxXqs1eF1OR3bBDyQenqXv3n4qqzASkyG46X8y0EYuRwGZWk4xTY6urfClkswx0S2H4xBQY4Z8mR6lkR2zr2DIpJFgxGTzZBJGaBnWlfG97/pp9jF7v2NqxSOj4MUfGPviXwOZ1UtKYiZwJ18tjPfLlV6GvoK7Ua7jOD9C7OTlIvVS726uFwBZgEenUUeqhAGlCpnXU5zCkHRNTLxBjVHeE+t/wJbrKhFSqGD12uupms0r8um3TCNIuyrivSs8S9sgC+QOn8irjFqkrTP3w48xXiZAOZ9F/FzBwl8BuZ6uWZ3Ho9bpAD69liIulU0K/Y/v6VHQS8Q6XV/0XQivhXIjirhMCmWia7i3/ipVGQn92HiR8CuzMHdC4tYJRsgkP1NOcLEPxeuBvDvCdNn2owYhMV418CjyEu3Efb6LIaUe8=
sudo: false
